import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navigation/navbar/theme";
import { ThemeProvider } from "next-themes";
import { Session } from "inspector/promises";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: {children: ReactNode;}) => {
  const session = await auth();
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <SessionProvider session={session}>
      <body className="min-h-screen flex flex-col relative">

  {/* BACKGROUND IMAGE LAYER */}
  <div className="fixed inset-0 -z-20">
    <img
      src="/images/popbg.png"
      alt="background"
      className="h-full w-full object-cover"
    />
  </div>

  {/* DARK OVERLAY LAYER */}
  <div className="fixed inset-0 bg-black/60 -z-10" />

  <ThemeProvider
    attribute="class"
    defaultTheme="system"
    enableSystem
    disableTransitionOnChange
  >
    <Navbar />

    {/* CONTENT LAYER */}
    <div className="relative z-10 flex-1">
      {children}
    </div>

  </ThemeProvider>

</body>
</SessionProvider>
    </html>
  );
}

export default RootLayout;